News week homepage (responsive design)
Bishoy-Samwel/NewsWeek-clone pull request #1
Opened 2021-01-25 15:45 UTC by Bishoy-Samwel

2021-01-25 17:00 UTC, Spayco requested changes
# Invalid 🛑 

Hello, you've made great progress, but I can't review your work unless the requirements below are met 👇 

- [x] The project should have a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
* [ ] Pull Request has a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))



Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-25 21:06 UTC, Spayco requested changes
# Invalid 🛑 

Hello, you've made great progress, but I can't review your work unless the requirements below are met 👇 

- [x] The project should have a descriptive README.md, yours is not descriptive enough. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))  - feel free to use [this template](https://github.com/microverseinc/readme-template)


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-26 11:20 UTC, PhillipUg requested changes
Hey team, 👋

You have done an amazing job implementing the requirements for this project.

However, there are still some changes 👇 you need to implement before moving on to your next milestone 🔍

### Changes Required ♻️ 

- [x] First of all, fix all linter errors. Kindly ensure to fix all linter errors before submitting for review in all your future projects

#### Header
- [x] The Newsweek logo has a link
    -  In desktop it is centered
    -  In tablet and mobile, it is aligned to the left
* [x] The Navbar contains a date only in desktop
* [ ] Login and Subscribe have links
  - In mobile, the Login button changes into an icon
* [ ] The main navigation (menu)
  - Uses a nav tag
  - Each option has a link
  - It has a form with the search field
  - In mobile and table the menu hides, and show a hamburger button
* [ ] The size of the elements change in desktop, tablet and mobile

#### Footer

* [ ] The Newsweek logo has a link
* [ ] The social media icons have links
* [ ] The content disposition changes to the correct place in desktop, tablet and mobile

#### Please note that this request will be approved in the dashboard and you don’t need to submit it for re-review or merge this request into the main branch please make the suggested changes and move on to the next milestone. When you're done with the next milestone, submit this request again, don't create a new pull request. You are to keep submitting this same pull request until project completion.

If you have any questions, feel free to send me a message through Slack as **Phillip Musiime** or
 <a href="mailto:phillipmusiime@gmail.com"> <img alt="gmail" src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social" target="_blank"></a> &nbsp; &nbsp; [![Twitter Follow](https://img.shields.io/twitter/follow/Phillip_Ug?style=social)](https://twitter.com/intent/follow?screen_name=Phillip_Ug) &nbsp; &nbsp; [![GitHub followers](https://img.shields.io/github/followers/phillipug?label=Follow&style=social)](https://github.com/PhillipUg)

2021-01-27 17:59 UTC, euqueme commented
Hello guys, :wave:  I see that the previous reviewer marked Milestone 1 as requested changes instead of Approved on the Dashboard, I see that you already worked on the whole project so that's really awesome keep it up! :muscle:  but since I cannot perform a re-review for this milestone I'm gonna approve it so you can submit for a code review for Milestone 2

I'm sorry for the bothers

Happy coding! :rocket:

2021-01-27 18:18 UTC, uryelah commented
### Invalid submission 🛑 

Hey Guys, I'm marking the submission for Milestone 3 as **INVALID** since you have not yet received the review for Milestone 2.

Please wait until you get Milestone 2 reviewed and then submit the review for Milestone 3 again 😃 

---

Happy coding 🍀

2021-01-27 19:54 UTC, jubaan requested changes
# Status: Approved with OBSERVATIONS :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] Style doesn't match original desing
- [ ] The widht of the middle column
- [ ] Debate section looks disproportionated
- [ ] My turn section is duplicated, and elements don't have the correct size
![image](https://user-images.githubusercontent.com/25774518/106042810-27e22580-60a3-11eb-9223-8c97f9432602.png)
- [ ] the free sign up element doesn't match the style and layout.
**Clone**
![image](https://user-images.githubusercontent.com/25774518/106043139-9a530580-60a3-11eb-9ce0-c8487eeb874d.png)
**Original**
![image](https://user-images.githubusercontent.com/25774518/106043173-a3dc6d80-60a3-11eb-81d5-ca3566030756.png)
- [ ] Sections missing or missing elements like titles are Culture and Travel, More Stories and Latest News, 
- [ ] Layout, style, dimensions don't match also in the Tablet view.
![image](https://user-images.githubusercontent.com/25774518/106043539-2ebd6800-60a4-11eb-8a15-cefca938d673.png)
![image](https://user-images.githubusercontent.com/25774518/106043612-4bf23680-60a4-11eb-9676-a8b90bfa4255.png)
![image](https://user-images.githubusercontent.com/25774518/106043669-5f050680-60a4-11eb-9217-c35444b583f0.png)
- [ ] The order in Mobile view of the elements in the column doesn't match the roginal
- [ ] Also the style, size and don't match the original
![image](https://user-images.githubusercontent.com/25774518/106043809-86f46a00-60a4-11eb-923f-11b5ced4b1c4.png)
![image](https://user-images.githubusercontent.com/25774518/106043963-b905cc00-60a4-11eb-9a25-1e66b02279ec.png)


## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!


<div>
  <div style="width:50px; height: 50px" align="center">
    <a href="https://avatars.githubusercontent.com/u/25774518?s=400&u=ae20ddf2d6fb3cae9e2f4044afe3b93d19e5b69e&v=4" alt="Julio Añoveros" title="@jubaan" width="100px" heigh="100px">
    </a>
  </div>
  </br>
  <p align="center">
    Julio Añoveros | @jubaan</br></br>
    <b>Full-stack Web Developer</b> and</br>
    Code Reviewer at <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a>:rocket:
  </p>
  <p align="center">
    <b>Feel stuck?</b></br>
    First breath... just do it.</br>
    Take 15-20 min away from the computer,</br>
    stretch, meditate, do some exercise, drink water,</br>
    or do whatever is necessary to distract your mind</br> 
    from the obstacle.</br></br> 
    Sometimes you just need to get away</br>
    to see things with a new perspetive.
  </p>
  <p align="center">
    <b>Need help?</b></br>
    Send me a DM in <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a> Students Slack,</br>
    you'll find me as @jubaan.
  </p>
  </br>
  <p align="center">
    <q>A <b>great programer</b> is not the one that knows it all,</br>
    but the one that ask a lot of question.</q></br></br>
    <b>Don't hesitate to ask for help!</b>
  </p>
</div>

2021-01-27 19:54 UTC, jubaan commented on index.html
> +          <div class="col-lg-4 col-md-5 col-sm-12">
- [ ] Use semantic HTML for `<main>`, `<article>`, `<section>`, `<h1>` to `<h6>` for titles, minimize the use of `div` containers they are generic and make it difficult to navigate through the HTML file. Semantic tags improve readability and reduces the complexity of the code. Review your HTML and apply semantic HTML

2021-01-27 19:54 UTC, jubaan commented on style.css
> +
- [ ] Remove ID, use custom CSS selectors to point out to the elements. Review all style.css file it should not contain ID, while it works on solving the issues it creates a difficult code to maintain in the long run.

2021-01-27 19:54 UTC, jubaan commented on style.css
> +    justify-content: left;
- Use bootstrap classes for **columns, flex, flex-direction, justify-content, align-content, display, position, font-weight, text-align**... etc. Review the style.css file and remove all CSS rules that have a Bootstrap class and is useful for the project.

2021-01-27 19:54 UTC, jubaan commented on style.css
> +    display: none !important;
- [ ] Remove all `!important` from the CSS stylesheet. don't override classes, and find a way whether with Bootstrap classes or with custom CSS is Bootstrap doesn't have a class for it.

2021-01-29 03:16 UTC, voscarmv requested changes
Hi. I accidentally deleted this review and was not able to undo the deletion, but here's a set of screenshots that I was able to extract from the edit history. You should be able to use these as the review:

![image](https://user-images.githubusercontent.com/2739245/106227834-a4622a80-61af-11eb-8023-651c511b8f3a.png)
![image](https://user-images.githubusercontent.com/2739245/106227847-b217b000-61af-11eb-8cb1-11b72b02a400.png)
![image](https://user-images.githubusercontent.com/2739245/106227883-bf349f00-61af-11eb-8ef9-0c9c9ab43112.png)
![image](https://user-images.githubusercontent.com/2739245/106227923-d7a4b980-61af-11eb-85c6-023b26073897.png)
![image](https://user-images.githubusercontent.com/2739245/106227938-e12e2180-61af-11eb-928c-7683016cd0fa.png)

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2021-01-29 03:16 UTC, voscarmv commented on style.css
> +}
- As mentioned earlier:
> Use bootstrap classes for columns, flex, flex-direction, justify-content, align-content, display, position, font-weight, text-align... etc. Review the style.css file and remove all CSS rules that have a Bootstrap class and is useful for the project.

2021-01-29 03:16 UTC, voscarmv commented on style.css
> +}
- As mentioned earlier:
> Use bootstrap classes for columns, flex, flex-direction, justify-content, align-content, display, position, font-weight, text-align... etc. Review the style.css file and remove all CSS rules that have a Bootstrap class and is useful for the project.

2021-01-29 11:11 UTC, karvel-code commented
Hello, We have made the necessary changes required by our reviewers. However, we have done our best to implement a bootstrap class for flex in the footer section but it is not leading to responsive results. Please advise.
Bishoy and Elvis.

2021-01-29 16:08 UTC, jubaan requested changes
# Status: Changes Required :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [x] Subscribe and Newsletter section should have the same height.
- [x] The Magazine Images in the Subscribe section are distorted, this should be fixed by working on the previous issue. But if it doesn't try `background-size: cover`
- [ ] Use Bootstrap classes instead of custom CSS rules, please review the inline comments previously commented by other reviewers. 
  - [ ] Display
  - [ ] Positions
  - [x] Flex direction
  - [ ] Flex wrap
  - [ ] Bold font
  - [x] Text alignment
  - [x] Text decoration
  - [x] background color (white, black)
- [ ] Remove the `!important` from the CSS styelsheet
- [x] Navbar menu elements should take the whole available space
![image](https://user-images.githubusercontent.com/25774518/106298707-d60fdb80-6219-11eb-8ec7-9d9389978346.png)


## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!



<div>
  <div style="width:50px; height: 50px" align="center">
    <a href="https://avatars.githubusercontent.com/u/25774518?s=400&u=ae20ddf2d6fb3cae9e2f4044afe3b93d19e5b69e&v=4" alt="Julio Añoveros" title="@jubaan" width="100px" heigh="100px">
    </a>
  </div>
  </br>
  <p align="center">
    Julio Añoveros | @jubaan</br></br>
    <b>Full-stack Web Developer</b> and</br>
    Code Reviewer at <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a>:rocket:
  </p>
  <p align="center">
    <b>Feel stuck?</b></br>
    First breath... just do it.</br>
    Take 15-20 min away from the computer,</br>
    stretch, meditate, do some exercise, drink water,</br>
    or do whatever is necessary to distract your mind</br> 
    from the obstacle.</br></br> 
    Sometimes you just need to get away</br>
    to see things with a new perspetive.
  </p>
  <p align="center">
    <b>Need help?</b></br>
    Send me a DM in <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a> Students Slack,</br>
    you'll find me as @jubaan.
  </p>
  </br>
  <p align="center">
    <q>A <b>great programer</b> is not the one that knows it all,</br>
    but the one that ask a lot of question.</q></br></br>
    <b>Don't hesitate to ask for help!</b>
  </p>
</div>

2021-01-29 16:10 UTC, jubaan commented
> Hello, We have made the necessary changes required by our reviewers. However, we have done our best to implement a bootstrap class for flex in the footer section but it is not leading to responsive results. Please advise.
> Bishoy and Elvis.

Please is better if you reach out through Slack you can find me as @jubaan.

2021-01-29 20:37 UTC, Spayco approved these changes
# Project Approved ✔️ 

thank you for making the required changes, your project is now approved!

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-29 21:03 UTC, merged